#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25
#  in conjunction with Tcl version 8.6
#    Jul 03, 2022 09:34:09 AM +0630  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def btn_add_item_action():
    print('add_item_support.btn_add_item_action')
    itemID = w.txt_item_id.get()
    itemName = w.txt_item_name.get()
    retail_price = int(w.txt_ratail_price.get())
    sale_price =  int(w.txt_sale_price.get())
    
    str_write = itemID+","+itemName+","+str(retail_price)+","+str(sale_price)+"\n"


    fielname = "items.txt"
    with open(fielname,"a") as fileWrite:
        fileWrite.writelines(str_write)

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import add_item
    add_item.vp_start_gui()




