#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25
#  in conjunction with Tcl version 8.6
#    Jul 03, 2022 09:34:09 AM +0630  platform: Windows NT

import sys
from item import item

from util import util

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


test_util =  util()

def btn_add_item_action():
    print('add_item_support.btn_add_item_action')
    itemID = w.txt_item_id.get().strip()
    itemName = w.txt_item_name.get().strip()
    retail_price = int(w.txt_ratail_price.get().strip())
    sale_price =  int(w.txt_sale_price.get().strip())
    category = str(w.txt_category_name.get().strip())
    
    str_write = itemID+","+itemName+","+str(retail_price)+","+str(sale_price)+"\n"

    cur_item = item(item_id=itemID,
    name=itemName,
    qr_code=itemID,
    price=sale_price,
    buying_price=retail_price,
    categories_id=category)

#    print(str_write)
#    print(cur_itme.getProfic())

    
    test_util.update_df(cur_item=cur_item)
    clean_data()

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    init_work()



def init_work(): 
    test_util.readExcelFile()
    item_id = test_util.get_latestID()
   
    w.txt_item_id.insert(tk.INSERT,item_id)

def clean_data():
    
    w.txt_item_id.delete(0, tk.END)
    w.txt_item_name.delete(0, tk.END)
    w.txt_ratail_price.delete(0, tk.END)
    w.txt_sale_price.delete(0, tk.END)
    w.txt_category_name.delete(0, tk.END)
    init_work()




def cal_profic():
    test_util.generate_proficCat_fig()







def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import add_item
    add_item.vp_start_gui()




